# Server
server.port=8080

# Database PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/talky
spring.datasource.username=tinah
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
app.jwt.secret=T0ky_S3cr3tK3y_V3ry_L0ng_For_S3cur1ty_Talky_App_2024
app.jwt.expiration=86400000

# CORS
app.cors.allowed-origins=http://localhost:5173

# CHANGEZ CECI TEMPORAIREMENT:
spring.jpa.hibernate.ddl-auto=update

# Logging
logging.level.com.talky=DEBUG
logging.level.org.springframework.web=DEBUG


spring.main.allow-circular-references=true